name: Build Sword Windows dependencies

on: [ repository_dispatch, push ]

jobs:
    build-win32:
        name: Build Sword Windows dependencies
        runs-on: windows-latest
        steps:
        - uses: ilammy/msvc-dev-cmd@v1
        - uses: actions/checkout@v1
        - uses: actions/checkout@v2
        - name: Checkout submodules
          shell: bash
          run: |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git lfs install --skip-smudge
            git submodule init
            git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update
            git lfs install --force
        - name: Build libraries
          run: powershell .\build_all.bat
          uses: actions/upload-artifact@master
          with:
            name: sword-deps-latest
            path: output
