name: Build Sword Windows binaries

on: [ repository_dispatch, push ]

jobs:
    build-win32:
        name: Build Sword & dependencies for Win32
        runs-on: windows-latest
        steps:
        - uses: ilammy/msvc-dev-cmd@v1
        - uses: actions/checkout@v1
        - uses: actions/checkout@v2
        - name: Checkout submodules
          shell: bash
          run: |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git lfs install --skip-smudge
            git submodule init
            git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update
            git lfs install --force
        - name: Create build directories
          shell: cmd
          run: |
            mkdir build
            mkdir build\lib
        - name: Build zlib
          run: powershell .\build_zlib.bat v1.2.9 build\lib
        - name: Build xz
          run: powershell .\build_xz.bat v5.2.4 build\lib
        - name: Build bzip2
          run: powershell .\build_bzip2.bat bzip2-1.0.8 build\lib
        - name: Build curl
          run: powershell .\build_curl.bat curl-7_68_0 build\lib
        - name: Build icu
          run: powershell .\build_icu.bat release-65-1 build\lib
        - name: Build sword
          run: powershell .\build_sword.bat e34fd3 build\lib
        - name: Upload artifacts
          uses: actions/upload-artifact@master
          with:
            name: sword-win32-build-latest
            path: build\lib
