name: Build Sword binaries

on: [ repository_dispatch, push ]

jobs:
    build-win32:
        name: Build Sword Windows binaries
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - name: Checkout submodules
        - uses: srt32/git-actions@v0.0.3
          with:
            args: git submodule update --init --recursive
        - uses: ilammy/msvc-dev-cmd@v1
        - name: Build zlib
          run: powershell .\build_zlib.bat
        - name: Build lzma
          run: powershell .\build_xz.bat
        - name: Build bzip2
          run: powershell .\build_bzip2.bat
        - name: Build curl
          run: powershell .\build_curl.bat
        - name: Build icu
          run: powershell .\build_icu.bat