name: Build Sword binaries

on: [ repository_dispatch, push ]

jobs:
    build-win32:
        name: Build Sword Windows binaries
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - uses: actions/checkout@v2
        - uses: ilammy/msvc-dev-cmd@v1
        - name: Checkout submodules
          shell: bash
          run: |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git submodule init
            git -c "http.extraheader=$auth_header" submodule update
            
#        - name: Install Windows build tools
#          run: powershell npm install windows-build-tools --vs2015
        - name: Build zlib
          run: powershell .\build_zlib.bat
        - name: Build liblzma
          run: powershell .\build_xz.bat