name: Build Sword binaries

on: [ repository_dispatch, push ]

jobs:
    build-win32:
        name: Build Sword Windows binaries
        runs-on: windows-latest
        steps:
        - uses: ilammy/msvc-dev-cmd@v1
        - uses: actions/checkout@v1
        - uses: actions/checkout@v2
        - name: Checkout submodules
          shell: bash
          run: |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git lfs install --skip-smudge
            git submodule init
            git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update
            git lfs install --force
        - name: Create output dir
          shell: cmd
          run: |
            mkdir output
        - name: Build zlib
          shell: cmd
          run: call build_zlib.bat output
        - name: Build lzma
          shell: cmd
          run: call build_xz.bat output
        - name: Build bzip2
          shell: cmd
          run: call build_bzip2.bat output
        - name: Build curl
          shell: cmd
          run: call build_curl.bat output
        - name: Build icu
          shell: cmd
          run: call build_icu.bat output