on:
  release:
    types: [created]

name: Build and publish binaries
jobs:
  build-win32:
    name: Build Sword Windows binaries
    runs-on: windows-latest
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git lfs install --skip-smudge
        git submodule init
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update
        git lfs install --force
    - name: Build libraries
      run: powershell .\build_all.bat
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: sword-win32-build-release
        path: build\lib

  release-win32:
    name: Publish Sword Windows binaries
    needs: build-win32
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@master
      with:
        name: sword-win32-build-release
    - name: Zip artifacts for publishing
      shell: bash
      run: |
        mv sword-win32-build-release sword-win32-build-${GITHUB_REF##*/}
        zip -9 -r sword-win32-build-${GITHUB_REF##*/}.zip sword-win32-build*
    - name: Publish artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'sword-win32-build-*.zip'