on:
  release:
    types: [created]

name: Build and publish binaries
jobs:
  build-win32:
    name: Build Sword Windows dependencies
    runs-on: windows-latest
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git lfs install --skip-smudge
        git submodule init
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update
        git lfs install --force
    - name: Build libraries
      run: powershell .\build_all.bat
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: sword-deps-release
        path: output

  release-win32:
    name: Publish Sword Windows dependencies
    needs: build-win32
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@master
      with:
        name: sword-deps-release
    - name: Zip artifacts for publishing
      shell: bash
      run: |
        mv sword-deps-release sword-deps-release-${GITHUB_REF##*/}
        zip -9 -r sword-deps-release-${GITHUB_REF##*/}.zip sword-deps-release*
    - name: Publish artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'sword-deps-release*.zip'